djangoWebsite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('contact/', views.contact),
    path('doctors/', views.getdoctors),
    path('hospitals/', views.hospitals),
    path('hospitals/<int:hospital_id>', views.hospitals),
    path('rate/<int:doctor_id>/<int:rating>/', views.rate),
    # path('blog/', views.posts),
    path('about/', views.about),
    path('userhome/', views.index),
    # path('hospitalhome/', views.index),
    path('doctors/', views.getdoctors),
    path('doctors/<int:id>', views.doctor_detail),
    # path('services/', views.services),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('hlogin/', views.hlogin),
    path('hregister/', views.hospital_register),
    # path('deneme/', views.deneme),
    path('captcha/', include('captcha.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from home import views

urlpatterns = [
    path('', views.index, name='home'),
    # path('userhome/', views.index, name='userhome'),
    # path('hospitalhome/', views.index, name='userhome'),
    path('logout/', views.logout_view, name='logout'),
    path('contact/', views.contact, name="contact"),
    path('hospitals/', views.hospitals, name='hospitals'),
    path('hospitals/<int:hospital_id>', views.hospital_detail, name='hospitals'),
    # path('<int:id>', views.hospitals, name='hospital'),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('about.html', views.about, name="about"),
    # path('blog-sidebar.html', views.posts, name="blog"),
    # path('hizmetler.html', views.services, name="services"),
    path('login/', views.login_view, name="login"),
    path('register/', views.register, name='signup'),
    path('doctors/', views.getdoctors, name='doctors'),
    path('edit_profile/', views.profile_edit, name='edit_profile'),
    # path('hlogin/', views.hlogin, name='hlogin'),
    path('hregister/', views.hospital_register, name='hregister'),
    path('doctors/<int:doctor_id>', views.doctor_detail, name='doctor_detail'),
    path('doctors/<int:doctor_id>/<int:comment_id>', views.delete_comment, name='delete_comment'),
    path('add_doctor', views.add_doctor, name='add_doctor'),
    path('view_doctors/', views.view_doctors, name='view_doctors'),
    path('view_doctors/delete/<int:doctor_id>/', views.doctor_delete, name='doctor_delete'),
    path('update_doctor/<int:doctor_id>', views.doctor_update, name='doctor_update'),
    path('view_appointments/', views.view_appointments, name='view_appointments'),
    path('view_appointments/change/<int:appointment_id>', views.appointment_done, name='appointment_done'),
    # path('deneme/', views.schedule_view, name='schedule_view'),
    path('appointment/', views.appointment, name='appointment'),
    path('appointments/cancel/<int:appointment_id>', views.appointment_cancel, name='appointment_cancel'),
    path('appointments/', views.user_appointments, name='appointments'),
    path('ajax/load_locations/', views.appointment_load_locations, name='ajax_load_locations'),
    path('ajax/load_hospitals/', views.appointment_load_hospitals, name='ajax_load_hospitals'),
    path('ajax/load_doctors/', views.appointment_load_doctors, name='ajax_load_doctors'),
    path('ajax/load_dates/', views.appointment_load_dates, name='ajax_load_dates'),
    path('ajax/load_times/', views.appointment_load_times, name='ajax_load_times'),
    # path('appointment_final/', views.appointment_final, name='appointment_final'),
    path('add_schedule/', views.add_schedule, name='add_schedule'),
    path('view_schedule/', views.view_schedule, name='view_schedule'),
    path('view_schedule/delete/<int:schedule_id>', views.delete_schedule, name='delete_schedule'),
]

home/views.py
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from . import forms
from home.forms import SignUpForm, HospitalSignUpForm, AddDoctorForm, AddHospitalForm, AddScheduleForm, \
    AppointmentForm, UserUpdateForm, ProfileUpdateForm, CommentForm
from django.core.mail import send_mail
from home.models import Menu, Doctor, Rating, Hospital, Speciality, Schedule, Location, Appointment, Patient, Status, \
    Times, Comment
from django.urls import reverse


# from datetime import time


def index(request):
    current_user = request.user
    if not current_user.is_anonymous:
        if current_user.is_staff:
            if request.method == 'POST':
                hospital = Hospital.objects.get(user=current_user)
                hregisterform = HospitalSignUpForm(request.POST, request.FILES, instance=current_user)
                hform = AddHospitalForm(request.POST, request.FILES, instance=hospital)
                if hform.is_valid() and hregisterform.is_valid():
                    user = hregisterform.save()
                    user.save()
                    hospital = hform.save()
                    hospital.save()
                    login(request, user)
                    return redirect('home:home')
            else:
                hospital = Hospital.objects.get(user=current_user)
                hregisterform = HospitalSignUpForm(instance=current_user)
                hform = AddHospitalForm(instance=hospital)
                return render(request, 'hospital/hospitalhome.html', {'hform': hform, 'hregisterform': hregisterform})
        else:
            patient = Patient.objects.get(user=current_user)
            if not patient is None:
                context = {
                    'user': User.objects.get(username=current_user),
                    'hospitals': Hospital.objects.all(),
                    'doctors': Doctor.objects.all(),
                    'patient': patient
                }
                return render(request, 'home/userhome.html', context)
            else:
                context = {
                    'user': User.objects.get(username=current_user),
                    'hospitals': Hospital.objects.all(),
                    'doctors': Doctor.objects.all(),
                }
                return render(request, 'home/userhome.html', context)
    context = {
        'hospitals': Hospital.objects.all(),
        'doctors': Doctor.objects.all(),
    }
    return render(request, "home/index.html", context)


@login_required(login_url='/login')
def profile_edit(request):
    current_user = request.user
    if not current_user.is_anonymous and not current_user.is_staff:
        patient = Patient.objects.get(user=current_user)
        if request.method == 'POST':
            user_form = UserUpdateForm(request.POST, instance=current_user)
            profile_form = ProfileUpdateForm(request.POST, instance=patient)
            if user_form.is_valid() and profile_form.is_valid():
                user_form.save()
                profile_form.save()
                return redirect('/')
        else:
            user_form = UserUpdateForm(instance=current_user)
            profile_form = ProfileUpdateForm(instance=patient)
        return render(request, 'home/userprofile.html', {'user_form': user_form, 'profile_form': profile_form})
    return redirect('/')


def login_view(request):
    if request.method == 'POST':
        loginform = forms.LoginForm(request.POST)
        if loginform.is_valid():
            username = loginform.cleaned_data.get("username")
            password = loginform.cleaned_data.get("password")
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/')
    else:
        loginform = forms.LoginForm()
    return render(request, 'registration/login.html', {'loginform': loginform})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')


def getdoctors(request: HttpRequest) -> HttpResponse:
    current_user = request.user
    doctors = Doctor.objects.all()
    specialities = Speciality.objects.all()

    if not current_user.is_anonymous and not current_user.is_staff:
        for doctor in doctors:
            rating = Rating.objects.filter(doctor=doctor, user=current_user).first()
            doctor.user_rating = rating.rating if rating else 0
        return render(request, template_name='home/userdoctor.html', context={'doctors': doctors,
                                                                              'specialities': specialities,
                                                                              'current_user': current_user})
    return render(request, template_name='home/doctor.html',
                  context={'doctors': doctors, 'current_user': current_user})


def doctor_detail(request: HttpRequest, doctor_id: int) -> HttpResponse:
    current_user = request.user
    doctor = Doctor.objects.get(id=doctor_id)
    comments = Comment.objects.filter(doctor=doctor)
    if not current_user.is_anonymous and not current_user.is_staff:
        cform = CommentForm(doctor=doctor)
        check_appointment = Appointment.objects.filter(user=current_user, doctor=doctor, status=4)
        user_rating = Rating.objects.filter(user=current_user, doctor=doctor)
        user_comments = Comment.objects.filter(user=current_user)

        if user_comments.count() < check_appointment.count():
            commentable = True  # if completed appointments are more than the number of comments, the user can make comments.
        else:  # user can make a single comment for each of their completed appointments.
            commentable = False
        if check_appointment:
            can_vote = True
        else:
            can_vote = False
        if request.method == 'POST':
            cform = CommentForm(doctor, request.POST)
            if cform.is_valid():
                cmt = cform.save(commit=False)
                cmt.user = current_user
                cmt.doctor = doctor
                cmt.save()
                cform.save()
                return redirect('doctor_detail', doctor_id)
        return render(request, 'home/userdoctorsingle.html', {'doctor': doctor, 'can_vote': can_vote,
                                                              'check_appointment': check_appointment,
                                                              'user_rating': user_rating,
                                                              'cform': cform, 'comments': comments,
                                                              'user': current_user,
                                                              'user_comments': user_comments,
                                                              'commentable': commentable})
    return render(request, template_name='home/doctorsingle.html', context={'doctor': doctor, 'comments': comments})


def delete_comment(request, doctor_id: int, comment_id: int):
    # current_user = request.user
    doctor = Doctor.objects.get(id=doctor_id)
    comment = Comment.objects.get(id=comment_id)

    comment.delete()
    return HttpResponseRedirect(reverse('doctor_detail', args=[doctor_id], ))


def hospitals(request):
    current_user = request.user
    # url_parameter = request.GET.get("")
    context = Hospital.objects.all()
    if not current_user.is_anonymous and not current_user.is_staff:
        return render(request, 'home/userhospital.html', context={'hospitals': context})
    return render(request, 'home/hospital.html', context={'hospitals': context})


def hospital_detail(request: HttpRequest, hospital_id: int) -> HttpResponse:
    hospital = Hospital.objects.get(id=hospital_id)
    doctors = Doctor.objects.filter(hospital=hospital)
    services = Speciality.objects.filter(doctor__in=doctors)
    current_user = request.user
    if not current_user.is_anonymous and not current_user.is_staff:
        return render(request, 'home/userhospitalsingle.html', context={'hospital': hospital, 'services': services})
    return render(request, 'home/hospitalsingle.html', context={'hospital': hospital, 'services': services})


def rate(request: HttpRequest, doctor_id: int, rating: int) -> HttpResponse:
    doctor = Doctor.objects.get(id=doctor_id)
    Rating.objects.filter(doctor=doctor, user=request.user).delete()
    doctor.rating_set.create(user=request.user, rating=rating)

    return getdoctors(request)


def contact(request):
    context = {
        'menus': Menu.objects.all(),
    }
    current_user = request.user

    if request.method == "POST":
        name = request.POST['name']
        email = request.POST['email']
        # phone = request.POST['phone']
        subject = request.POST['subject']
        message = request.POST['message']

        send_mail(
            '[MediGo]Message from ' + name + ': ' + subject,
            message,
            email,
            # phone,
            ['']
        )
        if not current_user.is_anonymous and not current_user.is_staff:
            return render(request, 'home/usercontact.html', context)
        return render(request, 'home/contact.html', context)
    else:
        if not current_user.is_anonymous and not current_user.is_staff:
            return render(request, 'home/usercontact.html', context)
        return render(request, 'home/contact.html', context)


def register(request):
    if request.method == 'POST':
        registerform = SignUpForm(request.POST)
        if registerform.is_valid():
            user = registerform.save()
            user.refresh_from_db()
            patient = Patient.objects.create(user=user)
            patient.user = user

home/templates/home/date_list.html
<<option value="">---------</option>
{% for date in dates %}
<option value="{{ date.id }}">{{ date.days }}</option>
{% endfor %}

home/templates/home/doctor_list.html
<<option value="">---------</option>
{% for doctor in doctors %}
<option value="{{ doctor.id }}">{{ doctor.name }}</option>
{% endfor %}

home/templates/home/hospital.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}
    <head>
        <title>
            Hastaneler
        </title>
    </head>
<body id="top">

    <section class="page-title bg-1">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="block text-center">
                        <span class="text-white">Hastaneler</span>
                        <h1 class="text-capitalize mb-5 text-lg">Hastaneler</h1>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <section class="section doctors">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6 text-center">
                    <div class="section-title">
                        <h2>Hastaneler</h2>
                        <div class="divider mx-auto my-4"></div>
                        <p>Başlık Hastaneler</p>
                    </div>
                </div>
            </div>
            <div class="row  portfolio-gallery">
                {% for hospital in hospitals %}
                    <div class="col-lg-3 col-sm-6 col-md-6">
                        <div class="position-relative doctor-inner-box">
                            <div class="doctor-profile">
                                <div class="doctor-img">
                                    <img src="{{ hospital.image.url }}" alt="" class="" width="200" height="200">
                                </div>
                            </div>
                            <div class="content mt-3">
                                <h3 class="mb-0"><a href="{{ hospital.id }}">{{ hospital.title }}</a></h3>
                                <p>{{ hospital.location }}</p>
                            </div>
                            <div class="row">
                                <h5>{{ hospital.info }}</h5>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
</body>
{% endblock %}

home/templates/home/hospital_list.html
<<option value="">---------</option>
{% for hospital in hospitals %}
<option value="{{ hospital.id }}">{{ hospital.title }}</option>
{% endfor %}

home/templates/home/location_list.html
<option value="">---------</option>
{% for location in locations %}
<option value="{{ location.pk }}">{{ location.name }}</option>
{% endfor %}

home/templates/home/userappointments.html
{% extends 'home/userbase.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% block content %}

<head>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.html5.min.js"></script>
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <script type="text/javascript" src="{% static 'js/datatables.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.dataTables.min.css">
    <title></title>
</head>
<body>

    <div id="wrapper" style="background-color: #b0ceff">

        <div class="page-content-wrapper">
            <div class="container-fluid"><a class="btn btn-link" role="button" id="menu-toggle" href="#menu-toggle"><i class="fa " style="color: black;"></i></a>
                <h2 class="text-center">Randevularım</h2>
                <section id="team" class="pb-5">
                    <div class="container">
                       <table class="table" id="example">
                           <!--table-hover-->
                            <thead>
                                <tr>
                                    <th>Klinik</th>
                                    <th>Şehir</th>
                                    <th>Hastane</th>
                                    <th>Doktor</th>
                                    <th>Tarih</th>
                                    <th>Saat</th>
                                    <th>Alındığı Tarih</th>
                                    <th>Durum</th>
                                    <th>CRUD</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for appointment in appointments %}
                                <tr style="color: black;">
                                    <td>{{ appointment.field }}</td>
                                    <td>{{ appointment.location }}</td>
                                    <td>{{ appointment.hospital }}</td>
                                    <td>{{ appointment.doctor }}</td>
                                    <td>{{ appointment.date.days }}</td>
                                    <td>{{ appointment.time }}</td>
                                    <td>{{ appointment.sent_date }}</td>
                                    <td>{{ appointment.status }}</td>
                                    <td id="crud_{{ appointment.id }}">
                                        &nbsp;
                                        &nbsp;
                                        <a href="{% url 'home:appointment_cancel' appointment_id=appointment.id %}"
                                           onclick="return confirm('İptal etmek istediğinize emin misiniz?')">
                                        <i class="bi bi-calendar-x" style="font-size: 18px; color: #e12454;" data-toggle="tooltip" title="İptal Et"></i>
                                        </a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </section>
            </div>
        </div>
    </div>
    <div class="scroll-top-wrapper"><span class="scroll-top-inner"><i class="fa fa-arrow-circle-up"></i></span></div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/back-to-top-scroll.js' %}"></script>
<script src="{% static 'js/Bold-BS4-Animated-Back-To-Top.js' %}"></script>
<script src="{% static 'js/bs-init.js' %}"></script>
<script src="{% static 'js/Sidebar-Menu.js' %}"></script>
</body>

{% endblock %}

home/templates/home/userdoctorsingle.html
{% extends 'home/userbase.html' %}
{% load widget_tweaks %}
{% load static %}
{% block content %}

    <head>
    <title>Doktor Bilgisi</title>
    </head>
    <body id="top">
    <link rel=”stylesheet” href=”https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css”rel=”nofollow” integrity=”sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm” crossorigin=”anonymous”>
    <section class="page-title bg-1">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="block text-center">
                        <span class="text-white">Doktor Sayfası</span>
                        <h1 class="text-capitalize mb-5 text-lg">{{ doctor.name }}</h1>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <section class="section doctor-single">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6">
                    <div class="doctor-img-block">
                        {% if doctor.image %}
                            <img src="{{ doctor.image.url }}" alt="" class="img-fluid w-100">
                        {% endif %}
                        {% if not doctor.image %}
                            <img src="{% static 'images/defaultd.png' %}" alt="" class="img-fluid w-100">
                        {% endif %}
                        <div class="info-block mt-4">
                            <h4 class="mb-0">{{ doctor.name }}</h4>
                            <p>{{ doctor.speciality }}</p>
                            <h5 class="card-title">
                                <span class="fa fa-star {% if doctor.average_rating > 0 %} checked {% endif %}"></span>
                                <span class="fa fa-star {% if doctor.average_rating > 1 %} checked {% endif %}"></span>
                                <span class="fa fa-star {% if doctor.average_rating > 2 %} checked {% endif %}"></span>
                                <span class="fa fa-star {% if doctor.average_rating > 3 %} checked {% endif %}" ></span>
                                <span class="fa fa-star {% if doctor.average_rating > 4 %} checked {% endif %}"></span>
                            </h5>
                            {% if can_vote %}
                                <p class="text-muted">
                                    Bu doktordan daha önce {{ check_appointment.count }} kere tedavi oldunuz.
                                </p>
                                <p class="text-muted">
                                    Daha önceki puanınız: {{ user_rating.rating }}
                                </p>
                            {% endif %}
                            {% if not can_vote %}
                                <p class="text-muted">
                                    Bu doktora puan vermek veya yorum yapmak için en az bir kere muayene olmanız gerekmektedir.
                                </p>
                            {% endif %}
                        </div>
                    </div>
                </div>

                <div class="col-lg-8 col-md-6">
                    <div class="doctor-details mt-4 mt-lg-0">
                        <h2 class="text-md">Biyografi</h2>
                        <div class="divider my-4"></div>
                        <h5>{{ doctor.hospital }}</h5>
                        <p>{{ doctor.biography }}</p>
                        <div class="row">
                            <a href="/appointment" class="btn btn-main-2 btn-round-full mt-3">Randevu Al<i class="icofont-simple-right ml-2  "></i></a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
        {% if commentable and can_vote %}
            <div class="row justify-content-center">
                <h2 style="color: #223a66">Yorum Yapın</h2>
            </div>
            <hr class="mx-n3">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">

                        <div class="row pl-3">
                            <p>Puanlayın (isteğe bağlı):</p>
                        </div>
                        <div class="row pl-3">
                            <ul class="btn btn-light list-inline rating-list">
                                <li onclick="rate(5, {{ doctor.id }})">
                                    <i class="fa fa-star {% if doctor.user_rating > 4 %} checked {% endif %}" title="Rate 5"></i></li>
                                <li onclick="rate(4, {{ doctor.id }})">
                                    <i class="fa fa-star {% if doctor.user_rating > 3 %} checked {% endif %}" title="Rate 4"></i></li>
                                <li onclick="rate(3, {{ doctor.id }})">
                                    <i class="fa fa-star {% if doctor.user_rating > 2 %} checked {% endif %}" title="Rate 3"></i></li>
                                <li onclick="rate(2, {{ doctor.id }})">
                                    <i class="fa fa-star {% if doctor.user_rating > 1 %} checked {% endif %}" title="Rate 2"></i></li>
                                <li onclick="rate(1, {{ doctor.id }})">
                                    <i class="fa fa-star {% if doctor.user_rating > 0 %} checked {% endif %}" title="Rate 1"></i></li>
                            </ul>
                        </div>

                        <form id="contact-form" class="contact__form" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-12">
                                    <div class="alert alert-success contact__msg" style="display: none" role="alert">
                                        Mesajiniz basariyla gonderildi.
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        {% render_field cform.title class+="form-control" placeholder="Başlık" %}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        {% render_field cform.comment_detail class+="form-control" placeholder="Yorumunuz" cols="240" rows="8"%}
                                    </div>
                                </div>
                            </div>
                            <div class="row pl-3">
                                <div class="text-center">
                                    <button class="btn btn-main btn-round-full" name="submit" type="submit">Yorum Yap</button>
                                </div>
                            </div>
                        </form>
                </div>
            </div>
        </div>
        {% endif %}
    </section>
    {{ cform.errors }}
    <section class="section">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="section-title">
                        <h2 class="mb-4">Yorumlar</h2>
                        <div class="divider  my-4"></div>
                    </div>
                </div>
            </div>
            {% if not comments %}
                <div class="row justify-content-left pl-3">
                    <p class="text-muted">
                        Henüz hiç yorum yapılmamış.
                    </p>
                </div>
            {% endif %}
            {% for comment in comments %}
                <div class="row card-body" style="background-color: #f8f9fa">
                    <div class="col-11">
                        <h4>{{ comment.title }}</h4>
                        <p>{{ comment.comment_detail }}</p>
                    </div>
                    {% if comment.user == user %}
                        <div class="col-1 pull-right">
                            <a href="{% url 'home:delete_comment' comment_id=comment.id doctor_id=doctor.id %}">
                                <button class="btn btn-sm" style="background-color: #e12454; color: #FFFFFF;"
                                    onclick="return confirm('Silmek istediğinize emin misiniz?')">
                                    Sil
                                </button>
                            </a>
                        </div>
                    {% endif %}
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <p class="text-muted">{{ comment.user.first_name}} {{ comment.user.last_name }} tarafından,
                            {{ comment.sent_date }} tarihinde gönderildi.</p>
                    </div>
                </div>
                <hr class="mx-n3">
            {% endfor %}

        </div>
    </section>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script>
        const rate = (rating, doctor_id) => {
            fetch(`/rate/${doctor_id}/${rating}/`, {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json'
                }
            }).then(rest => {
                window.location.reload();
            })
        }
    </script>

    </body>
{% endblock %}