djangoWebsite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('contact/', views.contact),
    path('doctors/', views.getdoctors),
    path('hospitals/', views.hospitals),
    path('hospitals/<int:hospital_id>', views.hospitals),
    path('rate/<int:doctor_id>/<int:rating>/', views.rate),
    # path('blog/', views.posts),
    path('about/', views.about),
    path('userhome/', views.index),
    # path('hospitalhome/', views.index),
    path('doctors/', views.getdoctors),
    path('doctors/<int:id>', views.doctor_detail),
    # path('services/', views.services),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('hlogin/', views.hlogin),
    path('hregister/', views.hospital_register),
    # path('deneme/', views.deneme),
    path('captcha/', include('captcha.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from home import views

urlpatterns = [
    path('', views.index, name='home'),
    # path('userhome/', views.index, name='userhome'),
    # path('hospitalhome/', views.index, name='userhome'),
    path('logout/', views.logout_view, name='logout'),
    path('contact/', views.contact, name="contact"),
    path('hospitals/', views.hospitals, name='hospitals'),
    path('hospitals/<int:hospital_id>', views.hospital_detail, name='hospitals'),
    # path('<int:id>', views.hospitals, name='hospital'),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('about.html', views.about, name="about"),
    # path('blog-sidebar.html', views.posts, name="blog"),
    # path('hizmetler.html', views.services, name="services"),
    path('login/', views.login_view, name="login"),
    path('register/', views.register, name='signup'),
    path('doctors/', views.getdoctors, name='doctors'),
    path('edit_profile/', views.profile_edit, name='edit_profile'),
    # path('hlogin/', views.hlogin, name='hlogin'),
    path('hregister/', views.hospital_register, name='hregister'),
    path('doctors/<int:doctor_id>', views.doctor_detail, name='doctor_detail'),
    path('doctors/<int:doctor_id>/<int:comment_id>', views.delete_comment, name='delete_comment'),
    path('add_doctor', views.add_doctor, name='add_doctor'),
    path('view_doctors/', views.view_doctors, name='view_doctors'),
    path('view_doctors/delete/<int:doctor_id>/', views.doctor_delete, name='doctor_delete'),
    path('update_doctor/<int:doctor_id>', views.doctor_update, name='doctor_update'),
    path('view_appointments/', views.view_appointments, name='view_appointments'),
    path('view_appointments/change/<int:appointment_id>', views.appointment_done, name='appointment_done'),
    # path('deneme/', views.schedule_view, name='schedule_view'),
    path('appointment/', views.appointment, name='appointment'),
    path('appointments/cancel/<int:appointment_id>', views.appointment_cancel, name='appointment_cancel'),
    path('appointments/', views.user_appointments, name='appointments'),
    path('ajax/load_locations/', views.appointment_load_locations, name='ajax_load_locations'),
    path('ajax/load_hospitals/', views.appointment_load_hospitals, name='ajax_load_hospitals'),
    path('ajax/load_doctors/', views.appointment_load_doctors, name='ajax_load_doctors'),
    path('ajax/load_dates/', views.appointment_load_dates, name='ajax_load_dates'),
    path('ajax/load_times/', views.appointment_load_times, name='ajax_load_times'),
    # path('appointment_final/', views.appointment_final, name='appointment_final'),
    path('add_schedule/', views.add_schedule, name='add_schedule'),
    path('view_schedule/', views.view_schedule, name='view_schedule'),
    path('view_schedule/delete/<int:schedule_id>', views.delete_schedule, name='delete_schedule'),
]

home/models.py
from ckeditor.fields import RichTextField
# from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import AbstractUser, User
from django.db import models
from django.core.validators import FileExtensionValidator, RegexValidator
from django.core.validators import validate_comma_separated_integer_list
from django.db.models import Avg
from django.utils import timezone

# Create your models here.


class Location(models.Model):
    name = models.CharField(max_length=30, blank=False)

    def __str__(self):
        return self.name


class Status(models.Model):
    name = models.CharField(max_length=20, blank=False, default=None)

    def __str__(self):
        return self.name


class Times(models.Model):
    time = models.TimeField(default=None, blank=True)

    def __str__(self):
        return str(self.time)


class Hospital(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=None)
    title = models.CharField(max_length=50)
    image = models.ImageField(blank=True, null=True, upload_to='images/')
    info = models.CharField(max_length=60, default=None, blank=True)
    about = RichTextField(blank=True)
    location = models.ForeignKey(Location, on_delete=models.CASCADE, blank=False)
    staff_count = models.IntegerField(default=0)
    # foundation_date = models.IntegerField(default=0)
    # bed_count = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def average_rating(self) -> float:
        return Rating.objects.filter(hospital=self).aggregate(Avg("rating"))["rating__avg"] or 0


class Speciality(models.Model):
    parent_id = models.BigIntegerField(default=0)
    name = models.CharField(max_length=40)
    sub_branch = models.BooleanField(default=False)
    parent_path = models.CharField(max_length=255, validators=[validate_comma_separated_integer_list], default=0)

    def __str__(self):
        return self.name


class Doctor(models.Model):

    name = models.CharField(max_length=40)
    image = models.ImageField(blank=True, upload_to='images/')
    description = models.CharField(max_length=80)
    # speciality = MultiSelectField(choices=Specialities.choices)
    # language = models.Languages
    biography = RichTextField(blank=True)
    video = models.FileField(blank=True, upload_to='videos')
    validator = [FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE, default=None, blank=False)
    speciality = models.ForeignKey(Speciality, on_delete=models.CASCADE, default=None, blank=False)

    def __str__(self):
        return self.name

    def average_rating(self) -> float:
        return Rating.objects.filter(doctor=self).aggregate(Avg("rating"))["rating__avg"] or 0


class Schedule(models.Model):

    All = 'Tüm saatler'
    Half = '30 Dakikada Bir'
    Exact = 'Saatte Bir'
    CHOICES = ((All, 'Tüm saatler'), (Half, '30 Dakikada Bir'), (Exact, 'Saatte Bir'))
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, blank=False)
    days = models.DateField(default=timezone.now, blank=True, null=True)
    time_interval = models.CharField(choices=CHOICES, default=None, blank=True, max_length=20)
    last_hour = models.ForeignKey(Times, on_delete=models.CASCADE, default=None, blank=False)
    # shift = models.BooleanField(default=False)      # False = tam gün çalışma, True = Yarım gün çalışma

    class Meta:
        unique_together = ["doctor", "days"]


class Appointment(models.Model):

    field = models.ForeignKey(Speciality, on_delete=models.RESTRICT, blank=False, default=None)
    location = models.ForeignKey(Location, on_delete=models.RESTRICT, blank=False, default=None)
    hospital = models.ForeignKey(Hospital, on_delete=models.RESTRICT, blank=False, default=None)
    doctor = models.ForeignKey(Doctor, on_delete=models.RESTRICT, blank=False, default=None)
    user = models.ForeignKey(User, on_delete=models.RESTRICT, blank=True, default=None)
    date = models.ForeignKey(Schedule, on_delete=models.RESTRICT, blank=False, default=None)
    time = models.ForeignKey(Times, on_delete=models.RESTRICT, blank=False, default=timezone.now)
    sent_date = models.DateField(auto_now_add=True)
    status = models.ForeignKey(Status, default=None, on_delete=models.RESTRICT, max_length=10, null=True)
    # is_active = models.BooleanField(blank=False, default=False)
    class Meta:
        ordering = ['-sent_date']


class Rating(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=False)
    # hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE, default=None, blank=True)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, default=None, blank=False)
    rating = models.IntegerField(default=0, blank=True)

    def __str__(self):
        return f"{self.doctor.name}: {self.rating}"


class Menu(models.Model):

    alphanumeric = RegexValidator(r'^[0-9a-zA-Z]*$', 'Yalnızca alfanumerik karakterler kabul edilir.')

    title = models.CharField(max_length=15, unique=True, validators=[alphanumeric])
    url = models.CharField(max_length=15, unique=True, validators=[alphanumeric])
    display = models.BooleanField()

    def __str__(self):
        return self.title


class Patient(models.Model):
    Male = 'Erkek'
    Female = 'Kadın'
    NotSpecified = 'Belirtilmedi'
    Gender_Choices = [(Male, 'Erkek'), (Female, 'Kadın'), (NotSpecified, 'Belirtilmedi')]

    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=False)
    weight = models.IntegerField(default=0, blank=True)
    height = models.IntegerField(default=0, blank=True)
    age = models.IntegerField(default=0, blank=True)
    gender = models.CharField(max_length=15, choices=Gender_Choices, default=NotSpecified, blank=True)


class Comment(models.Model):

    title = models.CharField(max_length=30)
    comment_detail = RichTextField(blank=False, default=None)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, blank=True)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, default=None, blank=True)
    # hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE, blank=True)
    sent_date = models.DateTimeField(auto_now_add=True)
    # rating = models.IntegerField(choices=CHOICES, default=None, blank=True)
    class Meta:
        ordering = ['-sent_date']
        unique_together = ['title', 'comment_detail']


# class Day(models.Model):
#     DAY_CHOICES = (
#         ("pazartesi", "Pazartesi"),
#         ("salı", "Salı"),
#         ("çarşamba", "Çarşamba"),
#         ("perşembe", "Perşembe"),
#         ("cuma", "Cuma"),
#         ("cumartesi", "Cumartesi"),
#     )
#
#     name = models.CharField(max_length=10, choices=DAY_CHOICES, blank=False, default="Pazartesi")
#
#     def __str__(self):
#         return self.name
    # day = models.ManyToManyField(Day)
    # timeblock = models.TimeField(default=timezone.now)

home/forms.py
from ckeditor.fields import RichTextField
from django import forms
# from django.contrib import admin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
# import datetime as dt

from django.forms import ModelChoiceField

from home.models import Doctor, Hospital, Schedule, Comment, Appointment, Location, Patient, Times

# Create your forms here.


class SignUpForm(UserCreationForm):
    username = forms.CharField(required=True, max_length=15)
    first_name = forms.CharField(required=True, max_length=15)
    last_name = forms.CharField(required=True, max_length=15)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class LoginForm(forms.Form):
    username = forms.CharField(required=True, max_length=15)
    password = forms.CharField(max_length=60, widget=forms.PasswordInput)


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Patient
        exclude = ('user',)


class HospitalSignUpForm(UserCreationForm):
    username = forms.CharField(required=True, max_length=30)
    password1 = forms.CharField(max_length=30, widget=forms.PasswordInput)
    password2 = forms.CharField(max_length=30, widget=forms.PasswordInput)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(HospitalSignUpForm, self).save()
        user.is_staff = True
        if commit:
            user.save()
        return user


class AddDoctorForm(forms.ModelForm):
    class Meta:
        model = Doctor
        exclude = ('hospital',)


class AddHospitalForm(forms.ModelForm):
    class Meta:
        model = Hospital
        exclude = ('user',)


class DateInput(forms.DateInput):
    input_type = 'date'


class AddScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ['doctor', 'days', 'time_interval', 'last_hour']
        widgets = {
            'days': DateInput()
        }

    def __init__(self, doctors, *args, **kwargs):
        super(AddScheduleForm, self).__init__(*args, **kwargs)
        self.fields['doctor'] = ModelChoiceField(queryset=doctors)
        self.fields['days'].widget.attrs.update({'min': '2023-01-12', 'max': '2023-03-01'})


class DeleteScheduleForm(forms.Form):
    doctor = forms.ModelChoiceField(queryset=Schedule.objects.filter(), required=True)
    days = forms.ModelChoiceField(queryset=Schedule.objects.values_list('days', flat=True), required=True)

    def __init__(self, doctors, *args, **kwargs):
        super(DeleteScheduleForm, self).__init__(*args, **kwargs)
        self.fields['doctor'] = ModelChoiceField(queryset=doctors)
        self.fields['days'] = ModelChoiceField(queryset=Schedule.objects.none())


class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        exclude = ('sent_date',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['field'].queryset = Speciality.objects.all()
        self.fields['location'].queryset = Location.objects.none()
        self.fields['hospital'].queryset = Hospital.objects.none()
        self.fields['doctor'].queryset = Doctor.objects.none()
        self.fields['date'].queryset = Schedule.objects.none()
        # self.fields['status'].queryset = Status.objects.filter(name='Inaktif')
        self.fields['status'].required = False
        self.fields['time'].queryset = Times.objects.none()
        # self.fields['user'].queryset = User.objects.none()
        # self.fields['status'].queryset =

    def is_valid(self):
        self.fields['location'].queryset = Location.objects.all()
        self.fields['hospital'].queryset = Hospital.objects.all()
        self.fields['doctor'].queryset = Doctor.objects.all()
        self.fields['date'].queryset = Schedule.objects.all()
        self.fields['time'].queryset = Times.objects.all()
        # self.fields['user'] =
        return super(AppointmentForm, self).is_valid()


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('sent_date',)

    def __init__(self, doctor, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        # self.fields['doctor'] = ModelChoiceField(queryset=Doctor.objects.filter(id=doctor.id))
        self.fields['doctor'].required = False

    def is_valid(self):
        return super(CommentForm, self).is_valid()

home/templates/hospital/admin_include.html
<div id="sidebar-wrapper">
    <ul class="sidebar-nav" style="padding-top: 90% ">
        <li><a></a></li>
        <li> <a href="/">Ana Sayfa</a></li>
        <li> <a href="/add_doctor">Doktor Ekle</a></li>
        <li> <a href="/view_doctors">Doktorları Görüntüle</a></li>
        <li> <a href="/add_schedule">Çalışma Günü Ekle</a></li>
        <li> <a href="/view_schedule">Çalışma Günleri</a></li>
        <li> <a href="/view_appointments">Randevuları Görüntüle</a></li>
        <li><a class="nav-link"></a></li>
        <li><a href="/logout" class="btn-primary btn-danger" style="color: #FFFFFF; size: 50px">Çıkış Yap<i class="icofont-simple-right ml-2  "></i></a></li>
    </ul>
</div>

home/templates/hospital/adminnav.html
{% load static %}
<style>
    .navbar {
        position: sticky;
    }
</style>
<nav class="navbar navbar-dark navbar-expand-md sticky-top bg-primary float-none sticky-top">
    <div class="container-fluid"><a class="navbar-brand text-center" href="#" style="margin: 0px 0px;">Hastane Sistemi</a>
    </div>
</nav>

home/templates/hospital/day_list.html
<<option value="">---------</option>
{% for day in days %}
<option value="{{ day.id }}">{{ day }}</option>
{% endfor %}

home/templates/hospital/view_doctors.html
{% load crispy_forms_filters %}
{% load static %}
{% include 'hospital/include.html' %}
{% include 'hospital/admin_include.html'%}
<head>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.html5.min.js"></script>
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <script type="text/javascript" src="{% static 'js/datatables.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.dataTables.min.css">
</head>
<body>
<section style="background-color: #22662C; min-height: 100vh; width: 100vw;">
    <div id="wrapper">

        <div class="page-content-wrapper">
            <div class="container-fluid"><a class="btn btn-link" role="button" id="menu-toggle" href="#menu-toggle"><i class="fa " style="color: black;"></i></a>
                <h2 class="text-center">Doktorlar</h2>
                <section id="team" class="pb-5">
                    <div class="container">
                       <table class="table" id="example">
                           <!--table-hover-->
                            <thead>
                                <tr>
                                    <th>Fotoğraf</th>
                                    <th>İsim</th>
                                    <th>Info</th>
                                    <th>Biyografi</th>
                                    <th>Hastane</th>
                                    <th>Uzmanlık</th>
                                    <th>CRUD</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for doctor in doctors %}
                                <tr style="color: black;">
                                    {% if doctor.image %}
                                        <td><img src="{{ doctor.image.url }}" alt="{{ doctor.name }}" width="50" height="50" style="border-radius: 50%"></td>
                                    {% endif %}
                                    {% if not doctor.image %}
                                        <td><img src="{% static 'images/defaultd.png' %}" alt="" width="50" height="50" style="border-radius: 50%"></td>
                                    {% endif %}
                                    <td>{{ doctor.name }}</td>
                                    <td>{{ doctor.description }}</td>
                                    <td>{{ doctor.biography }}</td>
                                    <td>{{ doctor.hospital }}</td>
                                    <td>{{ doctor.speciality }}</td>
                                    <td id="crud_{{doctor.id}}">
                                        <a href="{% url 'home:doctor_update' doctor_id=doctor.id %}">
                                        <i class="fas fa-pen" style="font-size: 18px; color: #b2d7fc;" data-toggle="tooltip" title="Update Doctor"></i>
                                        </a>
                                        &nbsp;
                                        <a href="{% url 'home:doctor_delete' doctor_id=doctor.id %}" onclick="return confirm('Are you sure to delete {{ doctor.name }}?')">
                                        <i class="fas fa-trash-alt" style="font-size: 18px; color: #ce0f0f;" data-toggle="tooltip" title="Delete Doctor"></i>
                                        </a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </section>
            </div>
        </div>
    </div>
    <div class="scroll-top-wrapper"><span class="scroll-top-inner"><i class="fa fa-arrow-circle-up"></i></span></div>
</section>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/back-to-top-scroll.js' %}"></script>
<script src="{% static 'js/Bold-BS4-Animated-Back-To-Top.js' %}"></script>
<script src="{% static 'js/bs-init.js' %}"></script>
<script src="{% static 'js/Sidebar-Menu.js' %}"></script>
</body>

home/templates/hospital/view_schedule.html
{% include 'hospital/include.html' %}
{% include 'hospital/admin_include.html' %}
{% load widget_tweaks %}
{% load static %}
{% block content %}
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.html5.min.js"></script>
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <script type="text/javascript" src="{% static 'js/datatables.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.dataTables.min.css">
    <section class="align-content-lg-center pl-lg-5 pt-lg-5 ml-5">
        <div class="container align-content-center emp-profile pl-5" style="margin-left: 200px">
            <div class="row justify-content-center pt-lg-5 pb-lg-5">
                <h2>Çalışma Günleri</h2>
                <table class="table" id="example" width="1000">
                    <thead>
                    <tr>
                        <th>Doktor</th>
                        <th>Gün</th>
                        <th>Çalışma Aralığı</th>
                        <th>Çıkış Saati</th>
                        <th>CRUD</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for schedule in schedules %}
                        <tr>
                            <td>{{ schedule.doctor }}</td>
                            <td>{{ schedule.days }}</td>
                            <td>{{ schedule.time_interval }}</td>
                            <td>{{ schedule.last_hour }}</td>
                            <td id="crud_{{ schedule.id }}">
                                &nbsp;
                                &nbsp;
                                <a href="{% url 'home:delete_schedule' schedule_id=schedule.id %}" onclick="return confirm('Are you sure to delete {{ doctor.name }}?')">
                                    <i class="fas fa-trash-alt" style="font-size: 18px; color: #ce0f0f;" data-toggle="tooltip" title="Delete Day"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </section>
    <style>
        body{
            background: #22662C;
        }
        .emp-profile{
            padding: 3%;
            margin-top: 3%;
            margin-bottom: 3%;
            border-radius: 0.5rem;
            background: #fff;
        }
        .profile-img{
            text-align: center;
        }
        .profile-img img{
            width: 70%;
            height: 100%;
        }
        .profile-img .file {
            position: relative;
            overflow: hidden;
            margin-top: -20%;
            width: 70%;
            border: none;
            border-radius: 0;
            font-size: 15px;
            background: #212529b8;
        }
        .profile-img .file input {
            position: absolute;
            opacity: 0;
            right: 0;
            top: 0;
        }
        .profile-head h5{
            color: #333;
        }
        .profile-head h6{
            color: #0062cc;
        }
        .profile-edit-btn{
            border: none;
            border-radius: 1.5rem;
            width: 70%;
            padding: 2%;
            font-weight: 600;
            color: #6c757d;
            cursor: pointer;
        }
        .proile-rating{
            font-size: 12px;
            color: #818182;
            margin-top: 5%;
        }
        .proile-rating span{
            color: #495057;
            font-size: 15px;
            font-weight: 600;
        }
        .profile-head .nav-tabs{
            margin-bottom:5%;
        }
        .profile-head .nav-tabs .nav-link{
            font-weight:600;
            border: none;
        }
        .profile-head .nav-tabs .nav-link.active{
            border: none;
            border-bottom:2px solid #0062cc;
        }
        .profile-work{
            padding: 14%;
            margin-top: -15%;
        }
        .profile-work p{
            font-size: 12px;
            color: #818182;
            font-weight: 600;
            margin-top: 10%;
        }
        .profile-work a{
            text-decoration: none;
            color: #495057;
            font-weight: 600;
            font-size: 14px;
        }
        .profile-work ul{
            list-style: none;
        }
        .profile-tab label{
            font-weight: 600;
        }
        .profile-tab p{
            font-weight: 600;
            color: #0062cc;
        }
    </style>
    <script>
        $("#id_doctor").change(function () {
            var url = $("#deleteScheduleForm").attr("data-days-url");
            var doctorId = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'doctor': doctorId
                },
                success: function (data) {
                    $("#id_days").html(data);
                }
            });

        });
        $(document).ready(function () {
            var table = $('#daysTable').DataTable();

            $.ajax({
                url: url,
                data: {
                    'doctor': doctorId
                },
                success: function (data) {
                    $("#id_days").html(data);
                }
            });
        });
    </script>

{% endblock %}